.PHONY: all testAdd testSubstract testMultiply testDivide testCompare testAssign Fractions clean
all: testAdd testSubstract testMultiply testDivide testCompare testAssign Fractions 

	
testAdd:
	g++ -o  testAdd Fraction.cpp testAdd.cpp
	
testSubstract:
	g++ -o  testSubstract Fraction.cpp testSubstract.cpp	
	
testMultiply:
	g++ -o  testMultiply Fraction.cpp testMultiply.cpp	
	
testDivide:
	g++ -o  testDivide Fraction.cpp testDivide.cpp
	
testCompare:
	g++ -o  testCompare Fraction.cpp testCompare.cpp
	
testAssign:
	g++ -o  testAssign Fraction.cpp testAssign.cpp

Fractions:
	g++ -o  Fractions Fraction.cpp main.cpp
	

